languageCode = "fr"
languageName = "French"
weight = 2
title = "Rayyan"
contentDir = 'content/fr'


[params]
  displayName = "FR"
  isoCode = "fr"
  rtl = false
  # logo = "img/logo.png"
  description = "O meu website awesome"
  # copyright = "Copy, _right?_ :thinking_face:"

dateFormat = "2 January 2006"

[params.author]
  name = "Rayyan Manzary"
  image = "img/avatar.png"
  headline = "mon site simple et étonnant"
  bio = "étudiant"
   links = [
     { github = "https://github.com/nunocoracao/blowfish" },
     { mail = "mailto:rayyanbc@gmail.com" }
   ]
