languageCode = "fr"
languageName = "French"
weight = 2
title = "Rayyan"
contentDir = 'content/fr'


[params]
  displayName = "FR"
  isoCode = "fr"
  rtl = false
  # logo = "img/logo.png"
  description = "O meu website awesome"
  # copyright = "Copy, _right?_ :thinking_face:"

dateFormat = "2 January 2006"

[params.author]
  name = "Gray Blowfish"
  image = "img/avatar.png"
  headline = "Um perfil simples com os meus links"
  bio = "A little bit about you"
   links = [
     { link = "https://nunocoracao.github.io/blowfish/" },
     { github = "https://github.com/nunocoracao/blowfish" },
     { x-twitter = "https://twitter.com/burufugu" }
   ]
