languageCode = "en"
languageName = "English"
weight = 1
title = "Rayyan"
contentDir = "content/en"

[params]
displayName = "EN"
isoCode = "en"
rtl = false
description = "My awesome website"
dateFormat = "2 January 2006"
author = { name = "Rayyan",
 image = "img/avatar.png", 
headline = "My awesome website", 
bio = "Lifelong Learner", 
links = [ { github = "https://github.com/rayyanmm" },
 { envelope = "mailto:rayyanbc@gmail.com" }  ] }
