languageCode = "ar"
languageName = "Arabic"
weight = 2
title = "Gray Blowfish"
contentDir = 'content/pt'


[params]
  displayName = "AR"
  isoCode = "ar"
  rtl = true
  # logo = "img/logo.png"
  description = "O meu website awesome"
  # copyright = "Copy, _right?_ :thinking_face:"

dateFormat = "2 January 2006"

[params.author]
  name = "Gray Blowfish"
  image = "img/avatar.png"
  headline = "a headline"
  bio = "A little bit about you"
   links = [
     { link = "https://nunocoracao.github.io/blowfish/" },
     { github = "https://github.com/nunocoracao/blowfish" },
     { x-twitter = "https://twitter.com/burufugu" }
   ]