languageCode = "ar"
languageName = "Arabic"
weight = 2
title = "Gray Blowfish"
contentDir = 'content/ar'


[params]
  displayName = "AR"
  isoCode = "ar"
  rtl = true
  # logo = "img/logo.png"
  description = "Arabic website"
  # copyright = "Copy, _right?_ :thinking_face:"

dateFormat = "2 January 2006"

[params.author]
  name = "Rayyan"
  image = "img/avatar.png"
  headline = "A headline"
  bio = "Lifelong learner"
   links = [
     { link = "https://nunocoracao.github.io/blowfish/" },
     { github = "https://github.com/nunocoracao/blowfish" },
     { x-twitter = "https://twitter.com/burufugu" }
   ]
